#!/usr/bin/env bash
#
# Install the launchd agents that keep Personal Assistant running and sweeping.
#
#   bash scripts/install-agents.sh            # install / refresh all three
#   bash scripts/install-agents.sh --status   # what's loaded right now
#   bash scripts/install-agents.sh --uninstall # remove all three
#
# Three agents, because the pieces depend on each other in one direction:
#
#   app       `npm run dev` on 127.0.0.1:4317, KeepAlive. Everything else
#             talks to it, so it has to be the one that's always up.
#   telegram  the long-polling relay. Calls OUT to Telegram and IN to the app
#             on loopback; needs no open port of its own.
#   pulse     the 08:00 staleness sweep. A scheduled trigger, not a daemon.
#
# WHY THIS SCRIPT EXISTS RATHER THAN A CHECKED-IN PLIST: launchd only accepts
# absolute paths, and a checked-in plist holding them goes stale the moment the
# project moves — a silent failure, because a scheduled job that cannot find its
# script simply never reports. Every path below is derived from where THIS FILE
# actually is, so moving the project and re-running this is the whole migration.

set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS_DIR="$HOME/Library/LaunchAgents"
PREFIX="local.personal-assistant"

NODE_BIN="$(command -v node || true)"
NPM_BIN="$(command -v npm || true)"
[ -n "$NODE_BIN" ] || { echo "node not found on PATH" >&2; exit 1; }
[ -n "$NPM_BIN" ] || { echo "npm not found on PATH" >&2; exit 1; }

# launchd hands a job a near-empty PATH — /usr/local/bin is not on it, so the
# node that runs your shell is not the node launchd would find. Homebrew's
# /opt/homebrew/bin matters too: document extraction shells out to LibreOffice,
# and without it every .docx conversion fails with ENOENT.
BIN_DIR="$(dirname "$NODE_BIN")"
LAUNCH_PATH="$BIN_DIR:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin"

LABELS=("$PREFIX.app" "$PREFIX.telegram" "$PREFIX.pulse")

# ---------------------------------------------------------------- helpers

plist_path() { echo "$AGENTS_DIR/$1.plist"; }

# NOT `launchctl list | grep -q`: grep -q exits on the first match, launchctl
# takes SIGPIPE, and `pipefail` then reports the match as a failure. Whether a
# label looked "loaded" depended on where it happened to sit in the output.
is_loaded() {
  local out
  out="$(launchctl list 2>/dev/null || true)"
  case "$out" in
    *"$1"*) return 0 ;;
    *) return 1 ;;
  esac
}

unload_one() {
  local label="$1" file
  file="$(plist_path "$label")"
  if is_loaded "$label"; then
    launchctl unload "$file" 2>/dev/null || true
  fi
}

load_one() {
  local label="$1" file
  file="$(plist_path "$label")"
  launchctl load "$file"
}

# ---------------------------------------------------------------- modes

if [ "${1:-}" = "--status" ]; then
  echo "APP_DIR: $APP_DIR"
  for label in "${LABELS[@]}"; do
    if is_loaded "$label"; then
      printf '  %-46s loaded\n' "$label"
    else
      printf '  %-46s not loaded\n' "$label"
    fi
  done
  echo
  echo "Port 4317:"
  lsof -nP -iTCP:4317 -sTCP:LISTEN 2>/dev/null || echo "  nothing listening"
  exit 0
fi

if [ "${1:-}" = "--uninstall" ]; then
  for label in "${LABELS[@]}"; do
    unload_one "$label"
    rm -f "$(plist_path "$label")"
    echo "removed $label"
  done
  echo "Done. The project itself is untouched."
  exit 0
fi

mkdir -p "$AGENTS_DIR" "$APP_DIR/data"

# ---------------------------------------------------------------- app

cat > "$(plist_path "$PREFIX.app")" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/install-agents.sh — do not hand-edit, re-run it. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$PREFIX.app</string>

  <key>ProgramArguments</key>
  <array>
    <string>$NPM_BIN</string>
    <string>run</string>
    <string>dev</string>
  </array>

  <key>WorkingDirectory</key>
  <string>$APP_DIR</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>$LAUNCH_PATH</string>
  </dict>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>

  <key>StandardOutPath</key>
  <string>$APP_DIR/data/app.log</string>
  <key>StandardErrorPath</key>
  <string>$APP_DIR/data/app.err.log</string>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------- telegram

cat > "$(plist_path "$PREFIX.telegram")" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/install-agents.sh — do not hand-edit, re-run it. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$PREFIX.telegram</string>

  <key>ProgramArguments</key>
  <array>
    <string>$NODE_BIN</string>
    <string>$APP_DIR/bot/telegram.mjs</string>
  </array>

  <key>WorkingDirectory</key>
  <string>$APP_DIR</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>$LAUNCH_PATH</string>
  </dict>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <!-- The bot exits if the app isn't answering yet. Don't spin on it. -->
  <key>ThrottleInterval</key>
  <integer>30</integer>

  <key>StandardOutPath</key>
  <string>$APP_DIR/data/telegram.log</string>
  <key>StandardErrorPath</key>
  <string>$APP_DIR/data/telegram.err.log</string>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------- pulse

cat > "$(plist_path "$PREFIX.pulse")" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/install-agents.sh — do not hand-edit, re-run it. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$PREFIX.pulse</string>

  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$APP_DIR/scripts/pulse.sh</string>
  </array>

  <key>WorkingDirectory</key>
  <string>$APP_DIR</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>$LAUNCH_PATH</string>
  </dict>

  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>8</integer>
    <key>Minute</key><integer>0</integer>
  </dict>

  <key>RunAtLoad</key>
  <false/>

  <key>StandardOutPath</key>
  <string>$APP_DIR/data/pulse.log</string>
  <key>StandardErrorPath</key>
  <string>$APP_DIR/data/pulse.err.log</string>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------- load

for label in "${LABELS[@]}"; do
  unload_one "$label"
  load_one "$label"
  echo "loaded $label"
done

echo
echo "APP_DIR: $APP_DIR"
echo "Logs:    $APP_DIR/data/{app,telegram,pulse}.{log,err.log}"
echo
echo "The app agent runs 'npm run dev'. To run the production server instead,"
echo "swap ProgramArguments to 'npm run start' and build first — dev is the"
echo "default because it needs no build step and picks up edits live."
